default: &default
  adapter: postgresql
  username: dev
  password:
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: 'eta_calculator_dev'

test:
  <<: *default
  database: 'eta_calculator_test'

production:
  <<: *default
  database: 'eta_calculator_prod'
  password: dev

stage:
  <<: *default
  database: 'eta_calculator_prod'
  password: dev